#!/bin/bash
SOURCE=$HOME/src

cd $SOURCE

#Search for projects checked out using subversion
find -maxdepth 2 -name '.svn' -exec dirname {} \;

#Search for projects checked out using git
for f in `find -maxdepth 2 -name '.git' -exec dirname {} \;`
do
    cd $f
    pwd
    cd $SOURCE
done

#Search for projects checked out using mercurial
find -maxdepth 2 -name '.hg' -exec dirname {} \;
