#!/usr/bin/env perl
use strict;
use warnings;

use DBI;

my $target = shift ;

# DB settings
my $host = "localhost" ;
my $database = "stargazer" ;
my $user = "root" ;
my $password = "ipe83" ;

my $dbh = DBI->connect("DBI:mysql:$database",
                       "$user", 
                       "$password")
    || die "Could not connect to database: $DBI::errstr";

my $sth = $dbh->prepare("SELECT path ".
                        "FROM dircounts ".
                        "ORDER BY count DESC LIMIT 7") ;
$sth->execute() ;

my $count = 1 ;

if (!$target) {
    print "+ change to directory with: f <number>\n" ;
}

while (my @row = $sth->fetchrow_array) {
  if ($target) {
    if ($count == $target) {
      $sth->finish() ;
      $dbh->disconnect();
      system(". cdto '@row'") ;
      exit ;
    }
  } else {
    my $home = $ENV{'HOME'} ;
    my $path = "@row" ;
    $path =~ s/$home/~/ ;
    print "${count}: $path\n" ;
  }
  $count++ ;
} 

$dbh->disconnect();
