#!/usr/bin/env perl
use strict;
use warnings;

use DBI;

my $target = shift ;

# DB settings
my $host = "localhost" ;
my $database = "stargazer" ;
my $user = "root" ;
my $password = "ipe83" ;

my $dbh = DBI->connect("DBI:mysql:$database",
                       "$user", 
                       "$password")
    || die "Could not connect to database: $DBI::errstr";

my $span = 1000 * 60 * 60 * 7 ;

my $q = "SELECT path ".
          "FROM dircounts ".
         "WHERE UNIX_TIMESTAMP(time) > UNIX_TIMESTAMP(now()) - $span ".
      "ORDER BY time DESC LIMIT 7" ;

my $sth = $dbh->prepare($q) ;

$sth->execute() ;

my $count = 1 ;

if (!$target) {
  print "+ change to directory with: r <number>\n" ;
}

while (my @row = $sth->fetchrow_array) {
  if ($target) {
    if ($count == $target) {
      $sth->finish() ;
      $dbh->disconnect();
      system(". cdto '@row'") ;
      exit ;
    }
  } else {
    my $home = $ENV{'HOME'} ;
    my $path = "@row" ;
    $path =~ s/$home/~/ ;
    print "${count}: $path\n" ;
  }
  $count++ ;
} 

$dbh->disconnect();
